import {
  LayoutDashboard,
  Inbox,
  Users,
  Briefcase,
  FolderKanban,
  CalendarDays,
  CheckSquare,
  Wallet,
  Receipt,
  CircleDollarSign,
  LineChart,
  Clapperboard,
  Images,
  Files,
  Plug,
  Shield,
  FileBarChart,
  Bell,
  Settings,
} from "lucide-react";

export const dashboardNav = [
  { href: "/dashboard", label: "Overview", icon: LayoutDashboard },
  { href: "/dashboard/inbox", label: "Inbox", icon: Inbox },
  { href: "/dashboard/leads", label: "Leads", icon: Users },
  { href: "/dashboard/clients", label: "Clients", icon: Briefcase },
  { href: "/dashboard/projects", label: "Projects", icon: FolderKanban },
  { href: "/dashboard/calendar", label: "Calendar", icon: CalendarDays },
  { href: "/dashboard/tasks", label: "Tasks", icon: CheckSquare },
  { href: "/dashboard/finance", label: "Finance", icon: Wallet },
  { href: "/dashboard/expenses", label: "Expenses", icon: Receipt },
  { href: "/dashboard/revenue", label: "Revenue", icon: CircleDollarSign },
  { href: "/dashboard/analytics", label: "Analytics", icon: LineChart },
  { href: "/dashboard/content", label: "Content Studio", icon: Clapperboard },
  { href: "/dashboard/portfolio", label: "Portfolio Manager", icon: Images },
  { href: "/dashboard/files", label: "Files", icon: Files },
  { href: "/dashboard/integrations", label: "Integrations", icon: Plug },
  { href: "/dashboard/team", label: "Team", icon: Shield },
  { href: "/dashboard/reports", label: "Reports", icon: FileBarChart },
  { href: "/dashboard/notifications", label: "Notifications", icon: Bell },
  { href: "/dashboard/settings", label: "Settings", icon: Settings },
];

export const publicNav = [
  { href: "/work", label: "Work" },
  { href: "/services", label: "Services" },
  { href: "/packages", label: "Packages" },
  { href: "/about", label: "About" },
  { href: "/process", label: "Process" },
  { href: "/testimonials", label: "Testimonials" },
  { href: "/contact", label: "Contact" },
];
