import { AuthShell } from "@/components/auth/shell";
import { Button, Field, inputClass } from "@/components/ui";

export const metadata = { title: "Enroll MFA" };

export default function MfaEnrollPage() {
  return (
    <AuthShell title="Protect this account" description="Owner and admin roles require TOTP from an authenticator app. Email must already be verified.">
      <ol className="list-decimal space-y-2 pl-5 text-sm text-soft-gray">
        <li>Open your authenticator app.</li>
        <li>Scan the QR code generated by Supabase Auth.</li>
        <li>Enter the six-digit code to finish enrollment.</li>
      </ol>
      <div className="my-6 grid h-40 place-items-center rounded-lg border border-dashed border-white/15 text-sm text-soft-gray">
        QR code appears here after a real MFA factor is created.
      </div>
      <form action="/mfa/verify" className="space-y-4">
        <Field label="Authenticator code" name="code">
          <input id="code" name="code" className={inputClass} required inputMode="numeric" />
        </Field>
        <Button type="submit" className="w-full">Verify and continue</Button>
      </form>
      <p className="mt-4 text-xs text-soft-gray">Recovery codes are shown once at generation and are never stored in plaintext in this app.</p>
      <Button href="/mfa/recovery" variant="ghost" className="mt-2 w-full">Recovery instructions</Button>
    </AuthShell>
  );
}
