-- Manual owner-membership bootstrap. NOT applied by the app.
-- Do not run against production until the owner supplies the Auth user UUID
-- and approves the change. Do not invent a UUID. Do not use profile metadata.
--
-- How the owner is recognized today
-- 1. Application: OWNER_EMAIL allowlist (default documented mailbox info@stsmedia.co).
-- 2. Phase 1 SQL: public.is_phase1_owner() compares auth.jwt() email to that same mailbox.
-- 3. Day 1 org tables: empty until a service-role insert creates organizations +
--    organization_members (role=owner, status=active) for that Auth user id.
--
-- Why this file is blocked until an owner decision
-- Replacing is_phase1_owner() with membership-only checks before that row exists
-- would lock the allowlisted owner out of Phase 1 os_* tables. This file therefore
-- does not replace is_phase1_owner().
--
-- Local-first test (required before any production change)
-- 1. On a disposable local stack, create a new Auth user for the allowlisted mailbox.
-- 2. That local UUID is synthetic. Do not treat it as the production owner UUID.
-- 3. Insert the membership below with the local organization id and local user id.
-- 4. Confirm /dashboard still opens and Business Settings save writes an audit row.
-- 5. Do not replace is_phase1_owner() after that local test until the production
--    Auth UUID is supplied and the same insert is approved for a non-production
--    hosted project, then production.
--
-- Owner action for a real project
-- 1. In the Supabase Auth dashboard, copy the UUID for the allowlisted owner user.
-- 2. Replace the two placeholders below.
-- 3. Run this on a non-production project first, with the service role.
-- 4. Confirm the owner can still open /dashboard.
-- 5. Only then approve replacing is_phase1_owner() in a later migration.
--
-- Placeholders (do not commit real UUIDs):
--   :organization_id  existing or new public.organizations.id
--   :owner_user_id    auth.users.id for the allowlisted owner

-- insert into public.organization_members (
--   organization_id,
--   user_id,
--   role,
--   status,
--   invited_at,
--   accepted_at
-- ) values (
--   ':organization_id'::uuid,
--   ':owner_user_id'::uuid,
--   'owner',
--   'active',
--   now(),
--   now()
-- );

select 'blocked: supply owner Auth UUID before inserting membership'::text as status;
